import 'zod-openapi/extend'

export { OpenCodeServer, createServer, getDefaultServerConfig } from './server/index.js'
export type { ServerConfig } from './server/index.js'
export { createDatabase, OpenCodeDatabase } from './database/client.js'
export type { DatabaseConfig } from './database/client.js'
export { ChatService } from './chat/service.js'
export type { ChatMessage, ChatSession, LLMProvider, ToolCall } from './chat/service.js'
export * from './tools/index.js'
export * from './prompts/index.js'
export * from './realtime/index.js'
export * from './utils/index.js'
